export interface ExchangeItem {
  id: string;
  name: string;
  cost: number;
  category: string;
}

export const EXCHANGE_ITEMS: ExchangeItem[] = [
  { id: '1', name: '甜甜圈耳墜', cost: 100, category: '限定' },
  { id: '2', name: '水蛇戒指', cost: 50, category: '裝備' },
  { id: '3', name: '無瑕玲瓏魔笛', cost: 50, category: '坐騎' },
  { id: '4', name: '老者水晶', cost: 50, category: '其他' },
  { id: '5', name: '哈迪斯裝甲', cost: 50, category: '其他' },
  { id: '6', name: '髮型樣式：黎明辦', cost: 50, category: '其他' },
  { id: '7', name: '管弦樂琴樂譜：雷轟電轉', cost: 50, category: '樂譜' },
  { id: '8', name: '演技教材：詛咒', cost: 50, category: '情感動作' },
  { id: '9', name: '演技教材：說明計畫', cost: 30, category: '情感動作' },
  { id: '10', name: '休閒外套裝備箱', cost: 30, category: '裝備' },
  { id: '11', name: '毛巾套裝', cost: 30, category: '裝備' },
  { id: '12', name: '金碟幣白金卡', cost: 30, category: '其他' },
  { id: '13', name: '火蛟角笛', cost: 30, category: '坐騎' },
  { id: '14', name: '月桂冠古卜角笛', cost: 30, category: '坐騎' },
  { id: '15', name: '幽夜神威魔笛', cost: 30, category: '坐騎' },
  { id: '16', name: '朱焰神威魔笛', cost: 30, category: '坐騎' },
  { id: '17', name: '盧恩置物架', cost: 20, category: '家具' },
  { id: '18', name: '莫古利書桌', cost: 20, category: '家具' },
  { id: '19', name: '林間涼亭', cost: 20, category: '家具' },
  { id: '20', name: '庭園工具架', cost: 20, category: '家具' },
  { id: '21', name: '群星壁掛', cost: 20, category: '家具' },
  { id: '22', name: '蜥蜴人玩偶', cost: 15, category: '寵物' },
  { id: '23', name: '紫水豪士上衣', cost: 15, category: '裝備' },
  { id: '24', name: '紫水豪士小袴', cost: 15, category: '裝備' },
  { id: '25', name: '紫水槍士上衣', cost: 15, category: '裝備' },
  { id: '26', name: '紫水槍士小袴', cost: 15, category: '裝備' },
  { id: '27', name: '紫水拳士上衣', cost: 15, category: '裝備' },
  { id: '28', name: '紫水拳士小袴', cost: 15, category: '裝備' },
  { id: '29', name: '紫水間士上衣', cost: 15, category: '裝備' },
  { id: '30', name: '紫水間士小袴', cost: 15, category: '裝備' },
  { id: '31', name: '紫水弓士上衣', cost: 15, category: '裝備' },
  { id: '32', name: '紫水弓士小袴', cost: 15, category: '裝備' },
  { id: '33', name: '紫水術士上衣', cost: 15, category: '裝備' },
  { id: '34', name: '紫水術士小袴', cost: 15, category: '裝備' },
  { id: '35', name: '紫水學士上衣', cost: 15, category: '裝備' },
  { id: '36', name: '紫水學士小袴', cost: 15, category: '裝備' },
  { id: '37', name: '陳舊的特殊地圖S1', cost: 15, category: '地圖' },
  { id: '38', name: '陳舊的特殊地圖S2', cost: 15, category: '地圖' },
  { id: '39', name: '陳舊的特殊地圖S3', cost: 15, category: '地圖' },
  { id: '40', name: '庫爾札斯西部高地詳細地圖', cost: 10, category: '地圖' },
  { id: '41', name: '德拉瓦尼亞山麓詳細地圖', cost: 10, category: '地圖' },
  { id: '42', name: '德拉瓦尼亞河谷詳細地圖', cost: 10, category: '地圖' },
  { id: '43', name: '基拉巴尼亞邊區詳細地圖', cost: 10, category: '地圖' },
  { id: '44', name: '基拉巴尼亞山區詳細地圖', cost: 10, category: '地圖' },
  { id: '45', name: '基拉巴尼亞湖區詳細地圖', cost: 10, category: '地圖' },
  { id: '46', name: '九宮幻卡：邦達斯那奇', cost: 10, category: '卡片' },
  { id: '47', name: '九宮幻卡：爬蟲', cost: 10, category: '卡片' },
  { id: '48', name: '九宮幻卡：月讀', cost: 7, category: '卡片' },
  { id: '49', name: '九宮幻卡：黑迪斯', cost: 7, category: '卡片' },
  { id: '50', name: '九宮幻卡：2P', cost: 7, category: '卡片' },
  { id: '51', name: '恩莫族人偶', cost: 7, category: '寵物' },
  { id: '52', name: '小犰狳', cost: 7, category: '寵物' },
  { id: '53', name: '管弦樂琴樂譜：天晴大鼓音頭', cost: 7, category: '樂譜' },
  { id: '54', name: '克里耶蘿蔔 x 5', cost: 5, category: '消耗品' },
  { id: '55', name: '魔法棱晶 (職業大師) x 10', cost: 1, category: '消耗品' }
];
